[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.build]
cmds = ["npm run build", "mkdir -p .next/standalone/.next", "cp -r public .next/standalone/public", "cp -r .next/static .next/standalone/.next/static"]

[start]
cmd = "node .next/standalone/server.js"
