[phases.setup]
nixpkgsArchive = 'ffeebf0acf3ae8b29f8c7049cd911b9636efd7e7'

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[phases.start]
cmds = ['chmod +x start-safe.sh && ./start-safe.sh']

[variables]
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'true'